### ISSUE TITLE
A question about multi-GPU training

### ISSUE THREAD

**Issue by sj6077** [Leavingseason/xDeepFM#17]
According to your paper, you used 4 GPUs together for the training. Did you update the model parameters across GPUs synchronously or asynchronously?

**Comment by Leavingseason** [comment]
Sorry for the ambiguity. We only used multiple GPUs for parameter searching. For each individual running, we only use one GPU.
Please let me know whether parallel/distributed training is indeed necessary for your application, I will consider to add this feature.

**Comment by sj6077** [comment]
I'm working for building a distributed system for recommender applications with deep neural networks. Do you know any applications that use distributed training?

**Comment by Leavingseason** [comment]
I think there are many tools with distributed implementation. 
In recommender system, you can take a look at these two repos:
https://github.com/facebookresearch/dlrm
https://github.com/microsoft/recommenders

**Comment by sj6077** [comment]
@Leavingseason, thanks! I'll take look at.
